using UnityEngine;
using UnityEngine.UI;

public class ColorChangeRoof : MonoBehaviour
{
    public Slider redSlider;
    public Slider greenSlider;
    public Slider blueSlider;
    public Light sceneLight;


    void Start()
    {
        // Alustaa Stroboskoopin pois päältä
        Debug.Log("Color change script started");

    }

    public void Update()
    {

        //Color newColor = new(redSlider.value, greenSlider.value, blueSlider.value);


        //sceneLight.color = Color.Lerp(sceneLight.color, newColor, Time.deltaTime / 0.5f);


        // float defaultRed = 1.0f;  // Oletusarvo punaiselle väriarvolle
        //  float defaultGreen = 1.0f;  // Oletusarvo vihreälle väriarvolle
        // float defaultBlue = 1.0f;  // Oletusarvo siniselle väriarvolle


        float defaultRed = 0.0f;  // Oletusarvo punaiselle väriarvolle
        float defaultGreen = 0.0f;  // Oletusarvo vihreälle väriarvolle
        float defaultBlue = 0.0f;  // Oletusarvo siniselle väriarvolle

        float redValue = redSlider.value;
        float greenValue = greenSlider.value;
        float blueValue = blueSlider.value;

        // Tarkista punaisen väriarvon asetus
        if (redValue == 0.0f)  // Tarkista, onko arvo nolla
        {
            redValue = defaultRed;  // Aseta oletusarvo, jos arvo on nolla
        }

        // Tarkista vihreän väriarvon asetus
        if (greenValue == 0.0f)  // Tarkista, onko arvo nolla
        {
            greenValue = defaultGreen;  // Aseta oletusarvo, jos arvo on nolla
        }

        // Tarkista sinisen väriarvon asetus
        if (blueValue == 0.0f)  // Tarkista, onko arvo nolla
        {
            blueValue = defaultBlue;  // Aseta oletusarvo, jos arvo on nolla
        }

        // Luo uusi väri uusilla arvoilla
        Color newColor = new Color(redValue, greenValue, blueValue);



        //oletusarvo

        // Color newColor = new Color(redSlider.value, greenSlider.value, blueSlider.value);
        sceneLight.color = newColor;

        Debug.Log("Color change script started" + sceneLight.color);

    }
}
