using UnityEngine;
using UnityEngine.SceneManagement;

public class NextSceneButton : MonoBehaviour
{
    // Mððritð seuraavan skenaarion nimi tai indeksi
    public string nextSceneName; // Tai voit kðyttðð my—s sceneIndex-muuttujaa

    // Voit my—s mððrittðð seuraavan skenaarion indeksin, jos haluat
    // public int nextSceneIndex;

    // Metodi, joka kðynnistðð seuraavan skenaarion, kun nappia painetaan
    public void LoadNextScene()
    {
        // Tarkista, onko seuraavan skenaarion nimi mððritelty
        if (!string.IsNullOrEmpty(nextSceneName))
        {
            // Lataa seuraava skenaario nimen perusteella
            SceneManager.LoadScene(nextSceneName);
        }
        // Voit my—s kðyttðð indeksið lataamaan seuraavan skenaarion
        // else if (nextSceneIndex >= 0)
        // {
        //     SceneManager.LoadScene(nextSceneIndex);
        // }
    }

    // Update-metodi suoritetaan jokaisella ruudunpðivityksellð
    void Update()
    {
        // Tarkista, onko vðlily—nti (spacebar) painettu
        if (Input.GetKeyDown(KeyCode.Space))
        {
            // Kutsu LoadNextScene-metodia ladataksesi seuraavan skenaarion
            LoadNextScene();
        }
    }
}
